# Generated by Django 3.2.5 on 2021-07-11 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='post_date'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
